// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgvutGR-qFENONqD6c0fvdAu8_FMwcZY',
    appId: '1:185929281797:web:57f7bf4b7a66a299a1476c',
    messagingSenderId: '185929281797',
    projectId: 'bloc-firebase-2474c',
    authDomain: 'bloc-firebase-2474c.firebaseapp.com',
    storageBucket: 'bloc-firebase-2474c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp7rs77Igx_qvE4fKpQ78seCN2hp2N27w',
    appId: '1:185929281797:android:5118b180a1715bdea1476c',
    messagingSenderId: '185929281797',
    projectId: 'bloc-firebase-2474c',
    storageBucket: 'bloc-firebase-2474c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaoSlKTEtwzYBYQ1CJA8yfQXAXjMdZiE',
    appId: '1:185929281797:ios:303b14ce3d519860a1476c',
    messagingSenderId: '185929281797',
    projectId: 'bloc-firebase-2474c',
    storageBucket: 'bloc-firebase-2474c.appspot.com',
    iosBundleId: 'com.example.blocPatternFirebaseTut',
  );
}
